use anyhow::Result;
use std::fs;
use std::path::{Path, PathBuf};

use crate::config::types::Directories;
use crate::constants::{
    CONFIG_FILENAME, FUNCTIONS_SUBDIR, SCHEMAS_SUBDIR, TABLES_SUBDIR, TYPES_SUBDIR, VIEWS_SUBDIR,
};

/// Create the basic project structure for a pgmt project
pub fn create_project_structure(project_dir: &PathBuf, schema_dir: &PathBuf) -> Result<()> {
    fs::create_dir_all(project_dir)?;

    let dir_defaults = Directories::default();
    let migrations_dir = project_dir.join(&dir_defaults.migrations);
    let baselines_dir = project_dir.join(&dir_defaults.baselines);
    let full_schema_dir = project_dir.join(schema_dir);

    fs::create_dir_all(&migrations_dir)?;
    fs::create_dir_all(&baselines_dir)?;
    fs::create_dir_all(&full_schema_dir)?;

    // Create schema subdirectories
    fs::create_dir_all(full_schema_dir.join(SCHEMAS_SUBDIR))?;
    fs::create_dir_all(full_schema_dir.join(TYPES_SUBDIR))?;
    fs::create_dir_all(full_schema_dir.join(TABLES_SUBDIR))?;
    fs::create_dir_all(full_schema_dir.join(VIEWS_SUBDIR))?;
    fs::create_dir_all(full_schema_dir.join(FUNCTIONS_SUBDIR))?;

    Ok(())
}

/// Generate pgmt.yaml configuration file
pub fn generate_config_file(options: &super::InitOptions, project_dir: &Path) -> Result<()> {
    let shadow_config = match &options.shadow_config {
        crate::prompts::ShadowDatabaseInput::Auto => "  shadow:\n    auto: true".to_string(),
        crate::prompts::ShadowDatabaseInput::Manual(url) => {
            format!("  shadow:\n    auto: false\n    url: {}", url)
        }
    };

    let dir_defaults = Directories::default();

    // Only include roles_file in config if it was specified/detected
    let roles_file_config = options
        .roles_file
        .as_ref()
        .map(|f| format!("\n  roles_file: {}", f))
        .unwrap_or_default();

    let config_content = format!(
        r#"# pgmt Configuration File
# Generated by pgmt init

# Database Configuration
databases:
  dev_url: {}
{}

# Directory Structure
directories:
  schema_dir: {}
  migrations_dir: {}
  baselines_dir: {}{}

# Object Management
objects:
  comments: {}
  grants: {}
  triggers: {}
  extensions: {}
"#,
        options.dev_database_url,
        shadow_config,
        options.schema_dir.display(),
        dir_defaults.migrations,
        dir_defaults.baselines,
        roles_file_config,
        options.object_config.comments,
        options.object_config.grants,
        options.object_config.triggers,
        options.object_config.extensions
    );

    let config_path = project_dir.join(CONFIG_FILENAME);
    std::fs::write(config_path, config_content)?;

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::commands::init::{BaselineCreationConfig, InitOptions, ObjectManagementConfig};
    use std::env;

    #[test]
    fn test_create_project_structure() {
        let temp_dir = env::temp_dir().join("pgmt_test_project_structure");
        let _ = std::fs::remove_dir_all(&temp_dir);

        let schema_dir = PathBuf::from("schema");
        create_project_structure(&temp_dir, &schema_dir).unwrap();

        let dir_defaults = Directories::default();

        // Check that directories were created
        assert!(temp_dir.join(&dir_defaults.migrations).exists());
        assert!(temp_dir.join(&dir_defaults.baselines).exists());
        assert!(temp_dir.join("schema").exists());
        assert!(temp_dir.join("schema/tables").exists());
        assert!(temp_dir.join("schema/views").exists());
        assert!(temp_dir.join("schema/functions").exists());
        assert!(temp_dir.join("schema/types").exists());
        assert!(temp_dir.join("schema/schemas").exists());

        // Cleanup
        let _ = std::fs::remove_dir_all(&temp_dir);
    }

    #[test]
    fn test_generate_config_file() {
        let temp_dir = env::temp_dir().join("pgmt_test_config");
        let _ = std::fs::remove_dir_all(&temp_dir);
        std::fs::create_dir_all(&temp_dir).unwrap();

        let options = InitOptions {
            project_dir: temp_dir.clone(),
            dev_database_url: "postgres://localhost/test_db".to_string(),
            shadow_config: crate::prompts::ShadowDatabaseInput::Auto,
            schema_dir: PathBuf::from("custom_schema"),
            import_source: None,
            object_config: ObjectManagementConfig::default(),
            baseline_config: BaselineCreationConfig::default(),
            tracking_table: crate::config::types::TrackingTable::default(),
            roles_file: None,
        };

        generate_config_file(&options, &temp_dir).unwrap();

        let config_path = temp_dir.join("pgmt.yaml");
        assert!(config_path.exists());

        let content = std::fs::read_to_string(&config_path).unwrap();
        let dir_defaults = Directories::default();

        assert!(content.contains("postgres://localhost/test_db"));
        assert!(content.contains("custom_schema"));
        assert!(content.contains("auto: true"));
        assert!(content.contains(&format!("migrations_dir: {}", dir_defaults.migrations)));
        assert!(content.contains(&format!("baselines_dir: {}", dir_defaults.baselines)));

        // Cleanup
        let _ = std::fs::remove_dir_all(&temp_dir);
    }
}
